apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: td1t5a7my-go 
  janus-idp.io/tekton: td1t5a7my-go
  backstage.io/kubernetes-id: td1t5a7my-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: td1t5a7my-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml