apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: td1t5a7my-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: td1t5a7my-go 
  name: td1t5a7my-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: td1t5a7my-go 
